home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add, name='add'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('delete/<int:pk>/', views.delete, name='delete'),
] 

story_5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace = 'home'))
]

home/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.

class Matkul(models.Model):
    nama_matkul = models.CharField(max_length=30)
    dosen = models.CharField(max_length=30)
    sks = models.IntegerField()
    deskripsi = models.CharField(max_length=50)
    semester = models.CharField(max_length=50)
    kelas = models.CharField(max_length=10)
    auto_now_add = True #timestamp

    def __str__(self) :
        return "{}. {}".format(self.id, self.nama_matkul)

home/forms.py
from django import forms
from .models import Matkul

class MatkulForm(forms.ModelForm):
    
    class Meta:
        model = Matkul
        fields = ('nama_matkul', 'dosen', 'sks', 'deskripsi', 'semester', 'kelas',) 

    widgets = {
        'nama_matkul' : forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Nama mata kuliah'
            }
        ),

        'dosen' : forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Nama dosen'
            }
        ),

        'sks' : forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Jumlah SKS'
            }
        ),

        'deskripsi' : forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'deskripsi'
            }
        ),

        'semester' : forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Semester'
            }
        ),

        'kelas' : forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'kelas'
            }
        ),
    }

home/views.py
from django.shortcuts import render, redirect
from .forms import MatkulForm
from django.http import HttpResponse
from django.shortcuts import redirect
from django.utils import timezone
from django.shortcuts import get_list_or_404, get_object_or_404
from django.contrib import messages
from .models import Matkul
from datetime import datetime

# Create your views here.

def index(request):
    matkuls = Matkul.objects.all()
    context = {'matkuls': matkuls}
    return render(request, 'home/index.html', context)


''' Membuat matkul baru '''
def add(request):
    form = MatkulForm(request.POST or None)
    print(request.POST)
    print(request.method)
    if request.method == 'POST':
        print("alhamdulillah masuk post")
        if form.is_valid():
            form.save()
            return(redirect('home:add'))
    context = {
        'Form': form
    }
    return render(request, 'home/add.html', context)


def matkul_edit(request, pk):
    matkul = get_object_or_404(matkul, pk=pk)
    if request.method == "POST":
        form = MatkulForm(request.POST, instance=matkul)
        if form.is_valid():
            matkul = form.save(commit=False)
            matkul.author = request.user
            matkul.published_date = timezone.now()
            matkul.save()
            return redirect('matkul_detail', pk=matkul.pk)
    else:
        form = MatkulForm(instance=matkul)
    return render(request, 'home/matkul-edit.html', {'form': form})

def detail(request, pk):
    matkul = Matkul.objects.get(id=pk)
    context = {
        'matkul': matkul, 
        }
    return render(request, 'home/matkul-detail.html', context)


def delete(request, pk):
    matkul = Matkul.objects.get(id=pk)
    matkul.delete()
    messages.success(request, (f"Mata Kuliah {matkul.nama_matkul} berhasil dihapus"))
    return render(request, 'home/index.html')

home/templates/home/add.html
<!DOCTYPE html>
<html lang="en">

{% extends 'home/base.html' %}
{% block content %}
{% include 'home/navbar.html' %}

{% load static %}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Hello</title>
</head>
<body>

<div class="container">
  <form method="POST">{% csrf_token %}

    <div class="form-group row">
      <label for="inputEmail3" class="col-sm-2 form-control-label">Nama Mata Kuliah</label>
      <div class="col-sm-10">
        {{ Form.nama_matkul }}
      </div>
    </div>
    
    <div class="form-group row">
      <label for="inputEmail3" class="col-sm-2 form-control-label">Nama Dosen</label>
      <div class="col-sm-10">
        {{ Form.dosen }}
      </div>
    </div>

    <div class="form-group row">
      <label for="inputEmail3" class="col-sm-2 form-control-label">Jumlah SKS</label>
      <div class="col-sm-10">
        {{ Form.sks }}
      </div>
    </div>

    <div class="form-group row">
      <label for="inputEmail3" class="col-sm-2 form-control-label">Deskripsi</label>
      <div class="col-sm-10">
        {{ Form.deskripsi }}
      </div>
    </div>

    <div class="form-group row">
      <label for="inputEmail3" class="col-sm-2 form-control-label">Semester</label>
      <div class="col-sm-10">
        {{ Form.semester }}
      </div>
    </div>

    <div class="form-group row">
      <label for="inputEmail3" class="col-sm-2 form-control-label">Kelas</label>
      <div class="col-sm-10">
        {{ Form.kelas }}
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit">Submit</button>
      </div>
    </div>
    
  </form>
</div>


{% endblock content %}

</body>
</html>

home/templates/home/base.html
{% load static %}
<html>
    <head>
        <title>Coolyeah!</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'home/style.css' %}">
    </head>
    <body>
    <h1><a href="/">Coolyeah!</a></h1>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">

{% extends 'home/base.html' %}
{% block content %}
{% include 'home/navbar.html' %}

{% load static %}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Matkul Keren</title>
</head>
<body>

    {% comment %} <div class="container my-4">
  {% if messages %}
	{% for message in messages %}
		<div class="alert alert-warning alert-dismissible fade show mt-4" role="alert">
			{{ message }}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
	{% endfor %}
	{% endif %} {% endcomment %}



  {% comment %} {% for matkul in matkuls %} 
    <div class="card mt-3">
      <div class="card-body d-flex justify-content-between flex-column flex-md-row">
          <div>
              <a href="{% url 'detail' matkul.id %}"><h5 class="card-title">{{ matkul.nama_matkul }}</h5></a>
              <h6 class="card-subtitle mb-2 text-muted">{{ matkul.semester }} {{ matkul.dosen }}</h6>
          </div>
          <a href="{% url 'delete' matkul.id %}" class="card-link text-danger mt-3 mt-md-0 mr-md-4 align-self-center">DELETE</a>
      </div>
    </div>
  {% endfor %}
  {% endcomment %}

  {% comment %} {% for matkul in matkuls %}
    {{ matkul.nama_matkul }} <br>
  {% endfor%} {% endcomment %}

  {% comment %} {% for matkul in matkuls %} 
    <div class="card mt-3">
      <div class="card-body d-flex justify-content-between flex-column flex-md-row">
          <div>
              <a href="{% url 'detail' matkul.id %}"><h5 class="card-title">{{ matkul.nama_matkul }}</h5></a>
              <h6 class="card-subtitle mb-2 text-muted">{{ matkul.semester }} {{ matkul.dosen }}</h6>
          </div>
          <a href="{% url 'delete' matkul.id %}" class="card-link text-danger mt-3 mt-md-0 mr-md-4 align-self-center">DELETE</a>
      </div>
    </div>
  {% endfor %} {% endcomment %}

{% for matkul in matkuls %}
  <div class="card">
  <div class="card-block">
    <h4 class="card-title">{{ matkul.nama_matkul }}</h4>
    <h6 class="card-subtitle mb-2 text-muted">{{ matkul.semester }}</h6>
    <p class="card-text">
      {{ matkul.deskripsi }}
    </p>
    <a href="{% url 'home:detail' matkul.id %}" class="card-link">DETAIL</a>
    <a href="{% url 'home:delete' matkul.id %}" class="card-link">DELETE</a>
  </div>
</div>
{% endfor matkul in matkuls %} 

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


{% endblock content %}



</body>
</html>

home/templates/home/matkul-detail.html
{% extends 'home/base.html' %}
{% block content %}
{% include 'home/navbar.html' %}
<div class="container my-4">
    <div class="jumbotron">
        <h1 class="display-4">{{ matkul.nama_matkul }}</h1>
        <p class="lead">{{ matkul.semester }}</p>
        <p>{{ matkul.deskripsi }}</p>
        <hr class="my-4">
        <div class="row">
            <h4 class="col-10 col-md-auto">Ruang : <span class="badge badge-light">{{ matkul.kelas }}</span></h4>
            <h4 class="col-10 col-md-auto">Dosen : <span class="badge badge-light">{{ matkul.dosen }}</span></h4>
            <h4 class="col-10 col-md-auto">Jumlah SKS : <span class="badge badge-light">{{ matkul.sks }} SKS</span></h4>
        </div>
        <a class="btn btn-outline-dark mt-4" href="{% url 'home:index' %}" role="button">BACK</a>
    </div>
</div>
{% endblock content %}


{% comment %} {% extends 'home/base.html' %}

{% block content %}
    <div class="matkul">
        {% if matkul.published_date %}
            <div class="date">
                {{ matkul.published_date }}
            </div>
        {% endif %}
        {% if user.is_authenticated %}
     <a class="btn btn-default" href="{% url 'matkul_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
{% endif %}
        <h2>{{ matkul.title }}</h2>
        <p>{{ matkul.text|linebreaksbr }}</p>
    </div>
{% endblock %} {% endcomment %}

home/templates/home/matkul-edit.html
{% extends 'home/base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="matkul-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

home/templates/home/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home:index' %}">Mata Kuliah</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home:index' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:add' %}">Add</a>
        </li>
      </ul>
    </div>
  </div>
  </nav>